version: "3.7"
services:
  #сервис базы данных
  db:
    #используем образ postgress
    image: postgres:16
    # назначаем имя для контейнера
    container_name: db_titanik
    #если запущена еще одна база данных, то лучше запустить не на
    #стандартном порту 5432 а на другом
    command: -p 1221
    expose: 
    - 1221
    #используем переменные для бд из env-non-dev
    env_file:
    - .env-non-dev

  #сервис приложения
  app:
  # готового image для нашего приложения нету.
  # необходимо использовать тот, что был написан самостоятельно в 
    build:
      # укажем положение докерфайла. если расположен там же где и этот файл, то пишем  . (точку)
      # если нет, то пишем /docker_folder/
      context: . 
    #используем переменные для бд из env-non-dev
    env_file:
      - .env-non-dev
    # containter_name: titanik_app2
    # укажем команду о миграций alembic. 
    #Для этого запустим команду из папки docker файла app.sh
    # для этого нужно из dockerfile убрать запуск gunicorn т.к. сначала запускается 
    # миграции а потом запускается сервер. это указываем в файле app.sh
    command: sh /fastapi_app/docker/app.sh
    # command: ["/docker/app.sh"]
    ports:
      - 9999:8000
    # указываем что приложение зависит от базы данных и redis
    depends_on:
      - db






